ispmailadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from graphene_django.views import GraphQLView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('sys_users/', include(('sys_users.urls', 'sys_users'), namespace="sys_users")),
    path('mail_manager/', include(('virtual.urls', 'virtual'), namespace="mail")),
    path('', login_required(TemplateView.as_view(template_name='main.html')), name="home")
]

virtual/urls.py
from django.urls import path, reverse, reverse_lazy
from django.views.generic import DeleteView, CreateView, ListView
from .views import BaseList
from .models import User, Domain, Alias
from .forms import UserForm, DomainForm

urlpatterns = [
    path('users/', BaseList.as_view(
        model=User,
        form_class=UserForm,
        paginate_by=10,
        success_url=reverse_lazy('mail:user_list'),
        ordering='-id'
    ), name="user_list"),
    path(
        'domains/',
        BaseList.as_view(
            model=Domain,
            form_class=DomainForm,
            paginate_by=10,
            success_url=reverse_lazy('mail:domain_list'),
            ordering='-id'
        ),
        name="domain_list"),
    path(
        'create_domain/',
        CreateView.as_view(
            model=Domain,
            form_class=DomainForm),
        name='domain_create'
    ),
    path(
        'delete_user/<int:pk>', DeleteView.as_view(
            model=User,
            success_url=reverse_lazy('mail:user_list'),
        ), name='user_delete'
    ),
    path(
        'delete_domain/<int:pk>',
        DeleteView.as_view(
            model=Domain,
            success_url=reverse_lazy('mail:domain_list'),
        ), name='domain_delete'
    ),
]

virtual/models.py
from django.db import models
from .lib import password
from django.core.validators import RegexValidator

# Create your models here.


"""
Estos modelos siguen el estandar creado por ISPmail 
si hay algo raro es que los nombres estan de acuerdo a ese estandar
Los nombres de las tablas están en plural por el estandar de ISPmail 
"""


class Domain(models.Model):
    """Dominos virtuales"""
    name = models.TextField(
        max_length=50,
        unique=True,
        validators=(
            RegexValidator(
                regex=r'^[a-zA-Z0-9-]*\.[a-z]*$',
                message="Enter a valid domain name"
            ),)
    )

    class Meta:
        db_table = 'virtual_domains'

    def __str__(self):
        return self.name


class User(models.Model):
    """Usuarios del correo electronico"""
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    email = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=100, blank=True, null=False, default=None)
    quota = models.BigIntegerField(default=0)

    __previous_password = None

    class Meta:
        db_table = 'virtual_users'

    def __init__(self, *args, **kwargs):
        super(User, self).__init__(*args, **kwargs)
        self.__previous_password = self.password

    def __str__(self):
        return self.email


    def save(self, *args, **kwargs):
        if not self.id:
            """si no hay ID es que es un nuevo usuario"""
            if self.password:
                """encripta el password"""
                self.password = password.crypt_pass(self.password)
            else:
                """
                Si es Usuario nuevo y no se ha definido password
                pwgen genera un password raw aleatorio y luego lo encipta
                """
                self.password = password.crypt_pass(password.pw_gen())
        else:
            """si es que hay id es que es un update"""
            if self.password != self.__previous_password:
                """significa que ha sido editado"""
                self.password = password.crypt_pass(self.password)
        super(User, self).save(*args, **kwargs)

    def quota_used(self):
        """Obtener la cuota del usuario via IMAP"""
        pass


class Alias(models.Model):
    """Alias y redirecciones"""
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    source = models.CharField(max_length=250)
    destination = models.CharField(max_length=250)

    class Meta:
        db_table = 'virtual_aliases'

virtual/forms.py
from django import forms
from django.forms.fields import EmailInput
from .models import User, Domain

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('email', 'domain', 'password', 'quota')
        widgets = {
            'password': forms.PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': "Password",
                'autocomplete': "new-password",
            }),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': "E-Mail"}),
            'domain': forms.Select(attrs={'class': 'custom-select'}),
            'quota': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Quota'})
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['domain'].empty_label = None


class DomainForm(forms.ModelForm):
    class Meta:
        model = Domain
        fields = {'name'}
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Dominio'})
        }

virtual/views.py
from django.views.generic import ListView, DeleteView, CreateView
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.admin.views.decorators import staff_member_required

from .models import User, Domain

# Create your views here.


@method_decorator(staff_member_required, name='dispatch')
class BaseList(LoginRequiredMixin, ListView, FormMixin):
    """Tiene el FormMixin pero tenemos que manejar nosotros el
     procesamiento del Form de otra forma es un dolor de trasero"""


    title = "Email Magnament"

    def __init__(self, *args, **kwargs):
        super(BaseList, self).__init__(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return redirect('virtual:user_list')

    def form_invalid(self, form):
        self.object_list = self.get_queryset()
        context = super().get_context_data()
        context['form'] = form
        return self.render_to_response(context=context)

templates/virtual/domain_list.html
{% extends 'main.html' %}
{% load static %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1>Domain List</h1>
      </div>
    </div>
    <hr/>
    {% if form.errors %}
      <div class="row">
        {{ form.errors }}
      </div>
    {% endif %}
    <form method="post">
      <div class="row">
        {% csrf_token %}
        <div class="col-12 col-md-3 mt-2 mt-md-auto">{{ form.name }}</div>
        <div class="col-12 col-md-3 mt-2 mt-md-auto">
          <button
              class="btn btn-outline-primary btn-block"
              type="submit"
          >
            New Domain
          </button>
        </div>
      </div>
    </form>
    <hr/>
    <div class="row">
      <div class="col-12">
        {% include 'pagination.html' %}
        <table class="table table-hover table-sm">
          <thead class="thead-dark">
          <tr>
            <th>id</th>
            <th>Domain</th>
            <th>Delete</th>
          </tr>
          </thead>
          <tbody>
          {% for domain in object_list %}
            <tr>
              <th>{{ domain.id }}</th>
              <td>{{ domain.name }}</td>
              <td>
                <button
                    class="btn btn-outline-danger"
                    id="button-delete-{{ domain.id }}"
                    onclick="get_modal({{ domain.id }},'{{ domain.name }}', '{% url 'mail:domain_delete' domain.id %}', '{{ csrf_token }}')"
                >
                  Eliminar
                </button>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
        {% include 'pagination.html' %}
      </div>
    </div>
  </div>

{% endblock %}

{% block js %}
  <script src="{% static 'js/delete_modal.js' %}"></script>

{% endblock %}

templates/virtual/user_list.html
{% extends 'main.html' %}
{% load static %}
{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1>User List</h1>
      </div>
    </div>
    <hr/>
    {% if form.errors %}
      <div class="row">
        {{ form.errors }}
      </div>
    {% endif %}
    <form method="post">
      <div class="row">
        {% csrf_token %}
        <div class="col-12 col-md-3 mt-2 mt-md-auto">{{ form.email }}</div>
        <div class="col-12 col-md-3 mt-2 mt-md-auto">{{ form.password }}</div>
        <div class="col-12 col-md-3 mt-2 mt-md-auto">{{ form.domain }}</div>
        <div class="col-12 col-md-3 mt-2 mt-md-auto">{{ form.quota }}</div>

      </div>
      <div class="row mt-2">
        <div class="col-12">
          <button
              class="btn btn-outline-primary btn-block"
              type="submit"
          >
            Nuevo usuario
          </button>
        </div>
      </div>
    </form>
    <hr/>
    <div class="row">
      <div class="col-12">
        {% include 'pagination.html' %}
        <table class="table table-hover table-sm">
          <thead class="thead-dark">
          <tr>
            <th>id</th>
            <th>email</th>
            <th>domain</th>
            <th>quota assigned</th>
            <th>quota used</th>
            <th>quota percent</th>
            <th>delete</th>
          </tr>
          </thead>
          <tbody>
          {% for user in object_list %}
            <tr>
              <th>{{ user.id }}</th>
              <td>{{ user.email }}</td>
              <td>{{ user.domain }}</td>
              <td>{{ user.quota }}</td>
              <td>---</td>
              <td>---</td>
              <td>
                <button
                    class="btn btn-outline-danger"
                    type="submit"
                    id="button-delete-{{ user.id }}"
                    onclick="get_modal({{ user.id }},'{{ user.email }}', '{% url 'mail:user_delete' user.id %}', '{{ csrf_token }}')"
                >
                  Eliminar
                </button>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
        {% include 'pagination.html' %}
      </div>
    </div>
  </div>
{% endblock %}
{% block js %}
  <script src="{% static 'js/delete_modal.js' %}"></script>
  <script>
    // TODO: arreglar cuando está mal escrito el dominio
    document.getElementById('{{ form.email.auto_id }}').addEventListener('change', e => {
      const domain = document.getElementById('{{ form.domain.auto_id }}').selectedOptions[0].innerHTML
      const re = /^(([^<>()\[\]\.,;:\s@\"]+(\.[^<>()\[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
      if (!e.target.value.match(re))
        e.target.value = `${e.target.value}@${domain}`;
      else{
        const address = e.target.value.split('@')[0];
        e.target.value = `${address}@${domain}`;
      }
    });

    document.getElementById('{{ form.domain.auto_id }}').addEventListener('change', e => {
      const email_input = document.getElementById('{{ form.email.auto_id }}');
      const [address, domain] = email_input.value.split('@');
      email_input.value = `${address}@${e.target.selectedOptions[0].innerHTML}`;
    })
  </script>
{% endblock %}