ispmailadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from graphene_django.views import GraphQLView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('sys_users/', include(('sys_users.urls', 'sys_users'), namespace="sys_users")),
    path('mail_manager/', include(('virtual.urls', 'virtual'), namespace="mail")),
    path('', login_required(TemplateView.as_view(template_name='main.html')), name="home")
]

sys_users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.views.generic import DeleteView
from .views import (
    LoginView,
    CompanyView,
    RemoveDomain,
    RemoveUser,
    RemoveEmail,
    ListEmailByDomain
)
from virtual.models import User as Email

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('company/<int:company_id>', CompanyView.as_view(), name="company"),
    path('company/', CompanyView.as_view(), name="company"),
    path('remove_domain/<int:company_id>/<int:pk>', RemoveDomain.as_view(), name="remove_domain"),
    path('remove_user/<int:company_id>/<int:pk>', RemoveUser.as_view(), name="remove_user"),
    path(
        'emails_by_domain/',
        ListEmailByDomain.as_view(),
        name="email_by_domain"
    ),
    path(
        'emails_by_domain/<int:company_id>/',
        ListEmailByDomain.as_view(),
        name="email_by_domain"
    ),
    path(
        'emails_by_domain/<int:company_id>/<int:domain_id>',
        ListEmailByDomain.as_view(),
        name="email_by_domain"
    ),
    path('remove_email/<int:company_id>/<int:domain_id>/<int:pk>', RemoveEmail.as_view(), name='remove_email')
]

virtual/urls.py
from django.urls import path, reverse, reverse_lazy
from django.views.generic import DeleteView, CreateView, ListView
from .views import BaseList
from .models import User, Domain, Alias
from .forms import UserForm, DomainForm

urlpatterns = [
    path('users/', BaseList.as_view(
        model=User,
        form_class=UserForm,
        paginate_by=10,
        success_url=reverse_lazy('mail:user_list'),
        ordering='-id'
    ), name="user_list"),
    path(
        'domains/',
        BaseList.as_view(
            model=Domain,
            form_class=DomainForm,
            paginate_by=10,
            success_url=reverse_lazy('mail:domain_list'),
            ordering='-id'
        ),
        name="domain_list"),
    path(
        'create_domain/',
        CreateView.as_view(
            model=Domain,
            form_class=DomainForm),
        name='domain_create'
    ),
    path(
        'delete_user/<int:pk>', DeleteView.as_view(
            model=User,
            success_url=reverse_lazy('mail:user_list'),
        ), name='user_delete'
    ),
    path(
        'delete_domain/<int:pk>',
        DeleteView.as_view(
            model=Domain,
            success_url=reverse_lazy('mail:domain_list'),
        ), name='domain_delete'
    ),
]

templates/main.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <script src="{% static 'fontawesome/js/fontawesome.min.js' %}"></script>
  <script src="{% static 'fontawesome/js/solid.min.js' %}"></script>
{% block head %}
{% endblock %}
{% block title %}
  <title>{{ title }}</title>
{% endblock %}
</head>
<body>
{% if user.is_authenticated %}
  {% include 'navbar.html' %}
{% endif %}

{% block body %}
{% endblock %}

<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
{% block js %}
{% endblock %}
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <a href="#" class="navbar-brand">MailManager</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a
            class="nav-link dropdown-toggle"
            href="#" id="magnamentDropdown"
            role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false"
        >
          Email Magnament
        </a>
        <div class="dropdown-menu" aria-labelledby="magnamentDropdown">
          {% if user.is_staff %}
            <a class="dropdown-item" href="{% url 'mail:domain_list' %}">global domains</a>
            <a class="dropdown-item" href="{% url 'mail:user_list' %}">global users</a>
            <a class="dropdown-item" href="">global redirections</a>
            <a class="dropdown-item" href="">global aliases</a>
          {% else %}
            <a class="dropdown-item" href="{% url 'sys_users:email_by_domain' %}">Email</a>
            {% block navbar %}

            {% endblock %}
          {% endif %}
        </div>

      </li>
      {% if user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sys_users:company' %}">Companies Magnament</a>
        </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="{% url 'sys_users:logout' %}" class="nav-link">Logout</a>
      </li>
    </ul>
  </div>
</nav>

templates/pagination.html
    <nav class="float-right" aria-label="navigation_Dispositivos">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.previous_page_number }}"
                       tabindex="-1"
                       aria-disabled="false">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link" tabindex="-1">
                        Anterior
                    </span>
                </li>
            {% endif %}

            {% if page_obj.number|add:'-4' > 1 %}
                <li>
                    <a href="?page={{ page_obj.number|add:'-5' }}"
                    class="page-link">
                        &hellip;
                    </a>
                </li>
            {% endif %}


            {% for page in page_obj.paginator.page_range %}

                {% if page_obj.number == page %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">
                        {{ page }}
                        <span class="sr-only">(current)</span>
                    </span>
                </li>
                {% elif page > page_obj.number|add:'-5' and page < page_obj.number|add:'5' %}
                    <li>
                        <a class="page-link" href="?page={{ page }}">
                            {{ page }}
                        </a>
                    </li>

                {% endif %}

            {% endfor %}

            {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                    <li>
                        <a href="?page={{ page_obj.number|add:'5' }}"
                           class="page-link">
                            &hellip;
                        </a>
                    </li>
                {% endif %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.next_page_number }}">
                        Siguiente

                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link"
                       >
                        Siguiente

                    </span>
                </li>
            {% endif %}

        </ul>
    </nav>