ispmailadmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from graphene_django.views import GraphQLView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    path('sys_users/', include(('sys_users.urls', 'sys_users'), namespace="sys_users")),
    path('mail_manager/', include(('virtual.urls', 'virtual'), namespace="mail")),
    path('', login_required(TemplateView.as_view(template_name='main.html')), name="home")
]

sys_users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.views.generic import DeleteView
from .views import (
    LoginView,
    CompanyView,
    RemoveDomain,
    RemoveUser,
    RemoveEmail,
    ListEmailByDomain
)
from virtual.models import User as Email

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('company/<int:company_id>', CompanyView.as_view(), name="company"),
    path('company/', CompanyView.as_view(), name="company"),
    path('remove_domain/<int:company_id>/<int:pk>', RemoveDomain.as_view(), name="remove_domain"),
    path('remove_user/<int:company_id>/<int:pk>', RemoveUser.as_view(), name="remove_user"),
    path(
        'emails_by_domain/',
        ListEmailByDomain.as_view(),
        name="email_by_domain"
    ),
    path(
        'emails_by_domain/<int:company_id>/',
        ListEmailByDomain.as_view(),
        name="email_by_domain"
    ),
    path(
        'emails_by_domain/<int:company_id>/<int:domain_id>',
        ListEmailByDomain.as_view(),
        name="email_by_domain"
    ),
    path('remove_email/<int:company_id>/<int:domain_id>/<int:pk>', RemoveEmail.as_view(), name='remove_email')
]

virtual/urls.py
from django.urls import path, reverse, reverse_lazy
from django.views.generic import DeleteView, CreateView, ListView
from .views import BaseList
from .models import User, Domain, Alias
from .forms import UserForm, DomainForm

urlpatterns = [
    path('users/', BaseList.as_view(
        model=User,
        form_class=UserForm,
        paginate_by=10,
        success_url=reverse_lazy('mail:user_list'),
        ordering='-id'
    ), name="user_list"),
    path(
        'domains/',
        BaseList.as_view(
            model=Domain,
            form_class=DomainForm,
            paginate_by=10,
            success_url=reverse_lazy('mail:domain_list'),
            ordering='-id'
        ),
        name="domain_list"),
    path(
        'create_domain/',
        CreateView.as_view(
            model=Domain,
            form_class=DomainForm),
        name='domain_create'
    ),
    path(
        'delete_user/<int:pk>', DeleteView.as_view(
            model=User,
            success_url=reverse_lazy('mail:user_list'),
        ), name='user_delete'
    ),
    path(
        'delete_domain/<int:pk>',
        DeleteView.as_view(
            model=Domain,
            success_url=reverse_lazy('mail:domain_list'),
        ), name='domain_delete'
    ),
]

sys_users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import DecimalValidator

# Create your models here.

class Company(models.Model):
    """Datos de la empresa que nos contrata el servicio"""
    name = models.CharField(max_length=50)
    id_number = models.CharField(max_length=11)  # RUC o DNI
    domain = models.ManyToManyField("virtual.Domain")

    def __str__(self):
        return self.name


class DomainAdmin(models.Model):
    """Datos del administador de dominio,
    tendrá un enlace directo al usuario de nuestro sistema"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=False, null=False)
    company = models.ManyToManyField('Company')

    def __str__(self):
        return self.user.username

sys_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    """Overiding the Authentication form"""
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'username'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'password'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'confirmation'

sys_users/views.py
from django.contrib.auth.views import LoginView, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import ListView, DeleteView

from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.db import transaction

from .models import Company, DomainAdmin
from .forms import CreateUserForm
from virtual.forms import DomainForm
from virtual.models import Domain, User as Email


# Create your views here.

class LoginView(LoginView):
    template_name = "sys_users/login.html"
    redirect_authenticated_user = True
    success_url = reverse_lazy("mail:user_list")
    title = "Login Email Magnament"


class sysUsers(LoginRequiredMixin, ListView):
    pass


@method_decorator(staff_member_required, name='dispatch')
class CompanyView(LoginRequiredMixin, ListView):
    model = Company
    ordering = '-id'
    paginate_by = 5
    title = "Email Magnament"
    domain_form = DomainForm
    user_form = CreateUserForm

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.title
        try:
            context['company'] = Company.objects.get(id=self.kwargs['company_id'])
            context['domain_form'] = self.domain_form
            context['user_form'] = self.user_form
            context['sys_user'] = DomainAdmin
        except KeyError as e:
            context['company'] = "---"

        return context

    @transaction.atomic
    def post(self, *args, **kwargs):
        if self.request.POST.get('form') == 'domain':
            """Si el formulario es de dominios"""
            form = DomainForm(self.request.POST)
            if form.is_valid():
                domain = form.save()
                company = Company.objects.get(id=self.request.POST.get('company_id'))
                company.domain.add(domain)
                return redirect('sys_users:company', self.request.POST.get('company_id'))
            else:
                self.object_list = self.get_queryset()
                context = self.get_context_data()
                context['domain_form'] = form
                return self.render_to_response(context)

        if self.request.POST.get('form') == 'user':
            """si el formulario es del usuarios"""
            form = CreateUserForm(self.request.POST)
            if form.is_valid():
                user = form.save()
                company = Company.objects.get(id=self.request.POST.get('company_id'))
                sys_user = DomainAdmin.objects.create(user=user)
                sys_user.company.add(company)
                return redirect('sys_users:company', self.request.POST.get('company_id'))
            else:
                self.object_list = self.get_queryset()
                context = self.get_context_data()
                context['user_form'] = form
                return self.render_to_response(context)


@method_decorator(staff_member_required, name='dispatch')
class RemoveDomain(LoginRequiredMixin, DeleteView):
    model = Domain

    def get_success_url(self):
        return reverse_lazy('sys_users:company', kwargs={'company_id': self.kwargs.get('company_id')})


@method_decorator(staff_member_required, name='dispatch')
class RemoveUser(LoginRequiredMixin, DeleteView):
    model = get_user_model()

    def get_success_url(self):
        return reverse_lazy('sys_users:company', kwargs={'company_id': self.kwargs.get('company_id')})


class ListEmailByDomain(LoginRequiredMixin, ListView):
    """Lista los emails por dominio, pero verificando la autenticacion,
     osea los dominios que le corresponden al usuario logueado"""
    title = "Email List By Domain"
    model = Email  # el queryset debe retornar los usuarios de emails
    paginate_by = 10
    companies = None
    domains = None
    template_name = 'sys_users/emails.html'

    def get_queryset(self):
        user = self.request.user.domainadmin
        self.companies = user.company.all()

        if self.kwargs.get('company_id'):
            """ Todos los dominios de la compañía seleccionada """
            if self.kwargs.get('domain_id'):
                """si es que hay domain_id en la url"""
                self.domains = self.companies.get(id=self.kwargs.get('company_id')).domain.all().filter(id=self.kwargs.get('domain_id'))
            else:
                self.domains = user.company.all().get(id=self.kwargs.get('company_id')).domain.all()
            emails = Email.objects.none()
            for domain in self.domains:
                emails = emails | domain.user_set.all()

        elif self.companies.__len__() == 1:
            """Cuando no hay company pero hay solo una"""
            self.domains = self.companies[0].domain.all()
            emails = Email.objects.none()
            for domain in self.domains:
                emails = emails | domain.user_set.all()
        else:
            """cuando no hay ni company_id 
            ni solo tiene una compañia
            tiene que devolver todos los dominios del usuario
            """

            self.domains = Domain.objects.none()
            for company in self.companies:  # crear queryset de todos los dominios
                self.domains = self.domains | company.domain.all()

            if self.kwargs.get('domain_id'):
                """esto esta muy hardcoded, hay que suavsarlo un poco"""
                self.domains = self.domains.filter(id=self.kwargs.get('domain_id'))

            emails = Email.objects.none()
            for domain in self.domains:
                emails = emails | domain.user_set.all()

        # configurando el filtro para la búsqueda
        if self.request.GET.get('email'):
            emails = emails.filter(email__icontains=self.request.GET.get('email'))

        return emails

    def get_context_data(self, *args, **kwargs):
        context = super(ListEmailByDomain, self).get_context_data(*args, **kwargs)
        context['companies'] = self.companies
        context['domains'] = self.domains
        context['emails'] = self.get_queryset  # Alias para los emails
        return context

class RemoveEmail(LoginRequiredMixin, DeleteView):
    model = Email

    def get_success_url(self):
        return reverse_lazy('sys_users:email_by_domain', kwargs={
            'company_id': self.kwargs.get('company_id'),
            'domain_id': self.kwargs.get('domain_id')
        })

templates/sys_users/company_list.html
{% extends 'main.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'bootstrap-select/bootstrap-select.min.css' %}">
{% endblock %}

{% block body %}
  <div class="container">

    <div class="row">
      <div class="col-12 {{ request.resolver_match.kwargs.company_id|yesno:"col-lg-8,," }}">
        <div class="col-12 text-center"><h1>Companies Managment</h1></div>
        {% include 'pagination.html' %}
        <table class="table table-hover table-sm">
          <thead class="thead-dark">
          <th>Company</th>
          <th>Company ID</th>
          <th>Domains</th>
          <th>Users</th>
          <th>Actions</th>
          </thead>
          {% for company in object_list %}
            <tr>
              <td>{{ company.name }}</td>
              <td>{{ company.id_number }}</td>
              <td class="small">
                {% for domain in company.domain.all %}
                  {{ domain }}<br/>
                {% endfor %}
              </td>
              <td class="small">
                {% for domainadmin in company.domainadmin_set.all %}
                  {{ domainadmin.user.username }} <br/>
                {% endfor %}
              </td>
              <td class="align-middle text-center">
                <a href="{% url 'sys_users:company' company.id %}" class="btn btn-outline-info"><i
                    class="fas fa-edit"></i></a>
                <button class="btn btn-outline-danger"><i class="fas fa-trash"></i></button>
              </td>
            </tr>
          {% endfor %}
        </table>
        {% include 'pagination.html' %}
      </div>
{#    ----------------------------------------------------------------------------------   #}
      {% if request.resolver_match.kwargs.company_id %}
        <div class="col-lg-4">
          <div class="container-fluid">
            <div class="row">

              <div class="col-10">
                <h2 class='text-center'>{{ company }}</h2>
              </div>

              <div class="col-2">
                <a class="btn btn-outline-secondary" href="{% url 'sys_users:company' %}">
                  <i class="fas fa-times"></i>
                </a>
              </div>
            </div>
            <hr/>
            <div class="row">
              <div class="col-8">
                <h4 class="text-center">Domains</h4>
              </div>
                <div class="col-2">
                <button id="new-domain-btn" class="btn btn-outline-secondary">
                  <i class="fas fa-plus"></i>
                </button>
              </div>
              <div class="col-2">
                <button class="btn btn-outline-secondary">
                  <i class="fas fa-users"></i>
                </button>
              </div>
            </div>
                <form id="new-domain-form" class="row d-none mt-3" action="" method="post">
                  {% csrf_token %}
                  <input type="hidden" name="company_id" value="{{ company.id }}">
                  <input type="hidden" name="form" value="domain">
                  <div class="row">
                    <div class="d-flex col-4 align-items-center">
                      <label class="m-0" for="{{ domain_form.name.auto_id }}">{{ domain_form.name.label }}</label>
                    </div>
                    <div class="col-6">
                      {{ domain_form.name }}
                    </div>
                    <div class="col-2">
                      <button class="btn btn-outline-primary" type="submit">
                        <i class="fas fa-plus"></i>
                      </button>
                    </div>
                  </div>
                </form>

            <div class="row text-danger">{{ domain_form.errors }}</div>
            <div class="row mt-3">
              <table class="table table-sm table-hover">
                <thead class="thead-light">
                <th>Domain</th>
                <th>Delete?</th>
                </thead>
                <tbody>
                {% for domain in company.domain.all %}
                  <tr>
                    <td>{{ domain }}</td>
                    <td class="text-center">
                      <button
                        onclick="get_modal('{{ domain.id }}', '{{ domain.name }}', '{% url 'sys_users:remove_domain' view.kwargs.company_id domain.id %}', '{{ csrf_token }}')"
                        class="btn btn-outline-danger"
                      >
                        <i class="fas fa-trash"></i>
                      </button>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
            <hr>
            <div class="row">
              <div class="col-8">
                <h4 class="text-center">Users</h4>
              </div>
              <div class="col-2">
                <button id="new-user-btn" class="btn btn-outline-secondary" type="button">
                  <i class="fas fa-user-plus"></i>
                </button>
              </div>
              <div class="col-2">
                <button id="chose-user-btn" class="btn btn-outline-secondary" type="button">
                  <i class="fas fa-people-arrows"></i>
                </button>
              </div>
            </div>
            <form id="new-user-form" class="row mt-3 d-none" action="" method="post">
              {% csrf_token %}
              <input type="hidden" name="company_id" value="{{ company.id }}">
              <input type="hidden" name="form" value="user">
              <div class="col-10">
                <div class="row">
                  <div class="col-12">{{ user_form.username }}</div>
                </div>
                <div class="row mt-1">
                  <div class="col-6">{{ user_form.password1 }}</div>
                  <div class="col-6">{{ user_form.password2 }}</div>
                </div>
              </div>
              <div class="d-flex col-2 align-items-center justify-content-center">
                <button class="btn btn-outline-primary" type="submit">
                  <i class="fas fa-plus"></i>
                </button>
              </div>
            </form>
            <div class="row text-danger">{{ user_form.errors }}</div>
            <div class="row mt-3">
                <table class="table table-sm table-hover">
                  <thead class="thead-light">
                  <th>Username</th>
                  <th>delete?</th>
                  </thead>
                  <tbody>
                  {% for user in company.domainadmin_set.all %}
                    <tr>
                      <td>{{ user }}</td>
                      <td class="text-center">
                        <button
                        onclick="get_modal('{{ user.user.pk }}', '{{ user.user.username }}', '{% url 'sys_users:remove_user' view.kwargs.company_id user.user.id %}', '{{ csrf_token }}')"
                        class="btn btn-outline-danger"
                      >
                        <i class="fas fa-trash"></i>
                      </button>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
            </div>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block js %}
  {% if request.resolver_match.kwargs.company_id %}
  <script>
    const toggle_block = (button, block) => {
      button.addEventListener("click", () => {
        block.classList.toggle('d-none');
        button.classList.toggle('btn-secondary');
        button.classList.toggle('btn-outline-secondary');
      })
    };
    toggle_block(document.getElementById('new-user-btn'), document.getElementById('new-user-form'));
    toggle_block(document.getElementById('new-domain-btn'), document.getElementById('new-domain-form'))
  </script>
    <script src="{% static 'js/delete_modal.js' %}"></script>
  {% endif %}
{% endblock %}

templates/sys_users/emails.html
{% extends 'main.html' %}
{% load static %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-12">
        <div class="list-group list-group-horizontal-lg flex-fill">
          {% for company in companies %}
            <a
                href="{% url 'sys_users:email_by_domain' company.id %}"
                class="list-group-item list-group-item-action"
            >
              {{ company.name }}
            </a>
          {% endfor %}
        </div>
      </div>
    </div>
    {% if domains %}
    <div class="row mt-5">
      <div class="col-12 col-lg-3">
        <div class="list-group">
          {% for domain in domains %}
            <a
            {% if view.kwargs.company_id %}
              href="{% url 'sys_users:email_by_domain' view.kwargs.company_id domain.id %}"
            {% else %}
              
              href="{% url 'sys_users:email_by_domain' '0' domain.id %}"
            {% endif %}
              class="list-group-item list-group-item-action"
            >

              {{ domain }}
            </a>
          {% endfor %}
        </div>
      </div>
      <div class=" col-12 col-lg-9">
      {% include 'pagination.html' %}
        <form action="" method="get">
        <table class="table table-sm table-hover">
          <thead class="thead-dark">
          <th id="email">
            <span>Email</span>
            <a href="#" class="search-button">
              <i class="ml-3 fas fa-search"></i>
            </a>
          </th>
          <th>Domain</th>
          <th>Quota</th>
          <th>Quota Used</th>
          <th>actions</th>
          </thead>
          <tbody class="small">
            {% for email in object_list %}
              <tr>
                <th>{{ email }}</th>
                <td>{{ email.domain }}</td>
                <td>{{ email.quota }}</td>
                <td>--</td>
                <td>
                  <button class="btn btn-outline-primary" type="submit">
                    <i class="fas fa-edit"></i>
                  </button>
                  <button
                      {% if view.kwargs.company_id %}
                      onclick="get_modal('{{ email.pk }}', '{{ email.email }}', '{% url 'sys_users:remove_email' view.kwargs.company_id email.domain.pk email.pk %}', '{{ csrf_token }}')"
                      {% else %}
                      onclick="get_modal('{{ email.pk }}', '{{ email.email }}', '{% url 'sys_users:remove_email' '0' email.domain.pk email.pk %}', '{{ csrf_token }}')"
                      {% endif %}
                      class="btn btn-outline-danger" type="button">
                    <i class="fas fa-trash"></i>
                  </button>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        </form>
      {% include 'pagination.html' %}
      </div>
    </div>
    {% endif %}
  </div>
{% endblock %}

{% block js %}
  <script src="{% static 'js/delete_modal.js' %}"></script>
  <script src="{% static 'js/search.js' %}"></script>
{% endblock %}

templates/sys_users/login.html
{% extends "main.html" %}

{% block body %}
<div class="d-flex h-100 w-100 position-absolute">
<div class="row m-auto">
<div class="col-12">
  {% if form.errors %}
    {{ form.errors }}
  {% endif %}
  <form method="post" action="{% url 'sys_users:login' %}" id="{{ form.auto_id }}">
    {% csrf_token %}
    <div class="mb-1">
      <label for="{{ form.username.auto_id }}">Username</label>
      {{ form.username }}
    </div>
    <div class="mb-1">
      <label for="{{ form.password.auto_id }}">Password</label>
      {{ form.password }}
    </div>
    <div class="d-flex justify-content-center">
    <button class="btn btn-outline-success">login</button>
    </div>
  </form>
</div>
</div>
</div>
{% endblock %}